import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { postPullRequestReview } from "@/lib/github";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id } = await params;

    const review = await prisma.review.findFirst({
      where: {
        id,
        userId: user.id,
      },
      include: {
        repository: {
          include: {
            user: true,
          },
        },
      },
    });

    if (!review) {
      return NextResponse.json({ error: "Review not found" }, { status: 404 });
    }

    if (!review.repository.user.githubAccessToken) {
      return NextResponse.json({ error: "GitHub token not available" }, { status: 400 });
    }

    if (review.status !== "COMPLETED") {
      return NextResponse.json({ error: "Review is not completed yet" }, { status: 400 });
    }

    const reviewBody = `## NeoForge AI Review

### Summary
${review.summary || "No summary available"}

### Strengths
${review.strengths ? JSON.parse(review.strengths as string).map((s: string) => `- ${s}`).join("\n") : "No strengths identified"}

### Issues Found
${review.issues ? JSON.parse(review.issues as string).map((i: { severity: string; message: string; line?: number }) => `- **[${i.severity.toUpperCase()}]** ${i.message}${i.line ? ` (line ${i.line})` : ""}`).join("\n") : "No issues found"}

### Suggestions
${review.suggestions ? JSON.parse(review.suggestions as string).map((s: { file: string; suggestion: string; code?: string }) => `**${s.file}**: ${s.suggestion}${s.code ? `\n\`\`\`\n${s.code}\n\`\`\`` : ""}`).join("\n\n") : "No suggestions"}

---
*Generated by NeoForge AI Code Review*`;

    await postPullRequestReview(
      review.repository.owner,
      review.repository.name,
      review.prNumber,
      review.repository.user.githubAccessToken,
      reviewBody
    );

    return NextResponse.json({ success: true, message: "Review posted to GitHub" });
  } catch (error) {
    console.error("Error posting review to GitHub:", error);
    return NextResponse.json({ error: "Failed to post review to GitHub" }, { status: 500 });
  }
}
